name: CI

# Triggers
on:
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    # Worker environment
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Test CI
      run: echo Hello, world!
