name: CI

# Triggers
on:
  pull_request:
    branches: [master]

jobs:
  unit-test:
    # Worker environment
    runs-on: node-lts-alpine3.12

    steps:
      # Checkout your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install the dependencies
        run: yarn

      - name: Test with jest
        run: yarn test
